### PR TITLE
Security fix and several lesser tweaks

### LINKED ISSUE #2: Data Leakge
There was a data leakage issue reported in LX3JL/xlxd (#83) about a year ago.  The reporter validly points out that there is a hard coded password in the xlxlog.php file that can be used for remote viewing of the /var/log/messages file.  However, it was closed by LX3JL without action.

I did a quick survey and find that the default hard coded password is present in many systems, including QuadNet systems.  Aside from the high risk of installers not changing the default, there is no  value in the QuadNet implementation continuing this "feature" as logging is done to the systemd journal.

I've removed the "log" directory from my working system and it continues to operate normally.  I intend to resolve the issue shortly via a pull request.

### PR DESCRIPTION
**Pull request by K2DLS**
1 - Fix #2 by removing the log directory from the dashboard.
2 - Update Makefile(s) to produce stripped binary for compactness.  Most end users do not require the debugging symbols in production.
3 - Put dmrid.dat in /var, which is where variable data goes, rather than in /usr/local/etc which is normally static configuration data.  Cosmetic but standard.
4 - Prefetch and install dmrid.dat if building XLX.

### CODE REVIEW

**Comment by w1bsb** [comment]
A couple of notes:

We don't strip binaries as this is a work in progress, and its very useful in debugging any issues we have. Obviously, this could be done on a per user basis.  I would suggest an option in the Makefile that turns stripping on or off on a per user basis, with the default being not to strip. This would also allow others using the software to provide debugging information to us that would otherwise be lost when stripping.

Regarding the DMRID file. xlxd by default loads the database into memory and does not actually download the file to disk. This feature would have to explicitly be turned on within xlxd itself to be of use.  At least, it hasn't on any of our systems. And it reloads that database once every 24 hours to keep it up to date.  I think this would make prefetching of the DMRID file pointless as well, unless a user has explicitly decided to now allow xlxd to download and store the file in memory.

**Comment by K2DLS** [comment]
What I'll do then is to put the options in the Makefile(s) and comment them out, along with a comment that describes when the installer might wish to use them.  That way all points of view are addressed.

**Comment by K2DLS** [comment]
Addressed points raised by @w1bsb .

**Comment by w1bsb** [comment]
Sorry. I just noticed you had also changed the location of the xlxd pidfile, but not the xrfd pidfile. These are defined in the default xlxd/xrfd configuration file for the webpage (config.inc.php) so those changes would need to be reverted, or the config.inc.php file updated. 

So in short, revert the pidfile location change, or update both xlxd/xrfd and their config.inc.php files respectively.  I don't see a problem with changing the location so long as those updates are made.

**Comment by K2DLS** [comment]
@w1bsb Colby, I believe that your most recent comment has been addressed.  Thanks for the review.

**Pull request merged**
